name: Mirror to GitLab

on:
  push:
    branches:
      - main 

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Push to GitLab
        run: |
          git config --global user.name "mirror-bot"
          git config --global user.email "mirror@example.com"
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.sanjijikfarm.com/root/BE.git
          git push --mirror gitlab
