on:
  push:
    branches:
      - '**'
  delete:
  create:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to GitLab
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
